export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MESSAGE_PENDING = 'SET_MESSAGE_PENDING';
export const SET_MESSAGE_FULFILLED = 'SET_MESSAGE_FULFILLED';
export const SET_MESSAGE_REJECTED = 'SET_MESSAGE_REJECTED';

export const HOME_SEARCH_INPUT_CHANGE = 'HOME_SEARCH_INPUT_CHANGE';

export const HOME_GET_CITIES = 'HOME_GET_CITIES';
export const HOME_GET_CITIES_PENDING = 'HOME_GET_CITIES_PENDING';
export const HOME_GET_CITIES_FULFILLED = 'HOME_GET_CITIES_FULFILLED';
export const HOME_GET_CITIES_REJECTED = 'HOME_GET_CITIES_REJECTED';
