export const APP_SET_SIZE = 'APP_SET_SIZE';

export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MESSAGE_PENDING = 'SET_MESSAGE_PENDING';
export const SET_MESSAGE_FULFILLED = 'SET_MESSAGE_FULFILLED';
export const SET_MESSAGE_REJECTED = 'SET_MESSAGE_REJECTED';

export const HOME_SEARCH_INPUT_CHANGE = 'HOME_SEARCH_INPUT_CHANGE';

export const HOME_GET_CITIES = 'HOME_GET_CITIES';
export const HOME_GET_CITIES_PENDING = 'HOME_GET_CITIES_PENDING';
export const HOME_GET_CITIES_FULFILLED = 'HOME_GET_CITIES_FULFILLED';
export const HOME_GET_CITIES_REJECTED = 'HOME_GET_CITIES_REJECTED';

export const ZONE_GET_ZONE = 'ZONE_GET_ZONE';
export const ZONE_GET_ZONE_PENDING = 'ZONE_GET_ZONE_PENDING';
export const ZONE_GET_ZONE_FULFILLED = 'ZONE_GET_ZONE_FULFILLED';
export const ZONE_GET_ZONE_REJECTED = 'ZONE_GET_ZONE_REJECTED';
