export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MESSAGE_PENDING = 'SET_MESSAGE_PENDING';
export const SET_MESSAGE_FULFILLED = 'SET_MESSAGE_FULFILLED';
export const SET_MESSAGE_REJECTED = 'SET_MESSAGE_REJECTED';


export const GETCITIES = 'GETCITIES';
export const GETCITIES_PENDING = 'GETCITIES_PENDING';
export const GETCITIES_FULFILLED = 'GETCITIES_FULFILLED';
export const GETCITIES_REJECTED = 'GETCITIES_REJECTED';
